version: '3.9'

services:

 mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: snapfd
    ports:
      - 3306:3306
      
 redis:
    image: "redis:6.2.6-bullseye"
    restart: always
    ports:
      - "6379:6379"
      
 order:
    image: "order:1.0.0"
    restart: always
    environment:
      REDIS_URI: redis:6379
    ports:
      - "3000:3000"
      
 order-process:
    image: "order-process:1.0.0"
    restart: always
    environment:
      MYSQL_URI: mysql:3306
      REDIS_URI: redis:6379
    ports:
      - "3002:3000"
